### PR TITLE
Support multiple AC units with MEL Cloud

### PR DESCRIPTION
**Pull request by klaamane**
I'm using MEL Cloud and I have two AC units. I had to add the following logic in order to get them  installed correctly (as child devices).  I've not been able to verify that this still works with only one unit but I don't see any reason why this would break anything.

Do you see any problems with this PR? Could you consider merging this into your version? Do you have the capability to test the single unit case?

### CODE REVIEW

**Comment by sburke781** [comment]
Certainly welcome any input from users of these drivers.  Thanks for taking the time to update, test and propose this change.  I'll take a look and let you know what I think about including it in the drivers more generally.

**Comment by sburke781** [comment]
That said, I will need to review the change in more detail.  I do remember needing to include some of the code you adjusted to accomodate some of the more recent

**Comment by sburke781** [comment]
Sorry, clicked the wrong button, and made the wrong comment when I mistakenly closed the PR.  I was thinking back to changes made to accommodate differences in the Kumo device details when users came on board with (I think it was) multiple units... But not in a MELCloud setup, hence my choice to try and "cancel" my comment, mistakenly cancelling the PR entirely.

So this is definitely something I will need to consider / look at in more detail.  Thanks for raising this PR.

**Comment by klaamane** [comment]
Great, please let me know if you want me to do some extra testing or other modifications.

**Comment by sburke781** [comment]
Do you have trouble with power status values as well?

**Comment by klaamane** [comment]
Yes I did. My last commit fixed them for me.

**Comment by sburke781** [comment]
We may need to look at this a little more.  I'm pretty sure it was Kumo where I saw this but I think there is a grouping option in some of the apps which produces difference Json.  Do you know if there is anything like that for your setup?

**Comment by sburke781** [comment]
@klaamane - Just wanted to let you know I haven't forgotten about this.  I am coordinating some testing of your changes with another user who has a setup that will make testing a single unit and multiple units easy to check my theory on needing to tweak your code slightly.  I will report back when we have an answer for this.

Thanks again for your efforts on this.
Simon

**Comment by sburke781** [comment]
Hi @klaamane ,

Sorry for the delay on this.

I am looking at exactly this same issue with another new user (without actually realising it :-) ).  I have finally cracked a major hurdle I have had from the start and can now view the setup JSON that is returned much more easily.  I want to confirm how the units come through for those with only one to see if they differ, then I can hopefully cater for both scenarios with some more confidence.

After all this time I'm now guessing your code will likely work for both single and multiple unit setups and my "replace" statements were masking the fact I had not included the [0] to pick up the first entry in the Devices array.

Simon

**Comment by sburke781** [comment]
I've been able to look at the structure of the JSON returned for a single device (A/C unit) and am much more confident that your solution will work like you expected.

There have been some changes since you committed your changes, so I will need to work through some merge conflicts, but I don't expect that to be too onerous.  I am hoping to have something ready for people to test quite soon.

**Comment by sburke781** [comment]
I ended up removing the boolean conversion for power = 1 or true, preferring for this to be more explicit in what it is catering for.

**Comment by sburke781** [comment]
My last commit most covered the updates to comments for version history in the two files and updates to the HPM repository manifest.

**Pull request merged**
