### PR TITLE
I subbed a PR then I think I cancelled it

### PR DESCRIPTION
**Pull request by jshimota01**
Hi Simon -
I made 2 small adjusts to your useful Date/Time Display app - which btw - I do use in my HE!

I added a debug on/off switch and I centered the HTML.  please consider these changes to your driver?
Shumo

### CODE REVIEW

**Comment by sburke781** [comment]
That looks fine Jim, at least at a glance on my phone 🙂. I'll take a closer look today or tomorrow and let you know.  I expect the only thing I may consider is whether to align the debug logging setting with how I gave done this in my other drivers I have done more recently.  I'll also see if there are any other tweaks I may want to make myself while I am in there.

Thanks for taking the time to make the changes and submit the PR.

Simon

**Comment by sburke781** [comment]
Looking at it again, I think I will introduce some of the same logging options I have used elsewhere.  I was thinking of introducing an info log entry to same that the auto polling had been changed or was currently disabled, but it would introduce a similar number of logs to what you are already trying to hide with the debug setting you introduced.  So I will probably introduce an info one as well, plus info log entries that are wrapped up in an info log setting like the one you introduced.  Probably a little bit of overkill on my part, but I'd prefer to keep it consistent within my own code base if I am going to change it.  And I can appreciate wanting to keep logs clean, I like that setup myself, so no arguments from me in wanting to introduce this change.

The only other thing I want to take a look at is how the formatting change affects existing date / time tiles.  Don't want to have existing users have their dashboard display differently.  Though, not having this in HPM is a saving grace....  I'll take a look.

**Comment by jshimota01** [comment]
Awesome! glad you took a moment on this - re: the centering, I never think of others - glad you did.  I use the Hubitat Android Dashboard from @jpage4500 and his tiles are so clean - I was just being anal.
Re the logging - I scan for 'debug' and 'warns' - so thats a bit more important to me!

Cancelling PR in anticipation... btw - not sure if you're using versioning so let me know when you release so I can manually 'repair' via HPM.

**Comment by sburke781** [comment]
No worries.  I'll try and wrap up a few changes in one then, logging, formatting and getting this into HPM.

**Pull request closed without merging**
