### PR TITLE
Update MELCloudParent_driver.groovy

### PR DESCRIPTION
**Pull request by JasperVanLeeuwen**
set language to 0 (english) per default. (language settings are retained and this changes the language settings in my android app)

### CODE REVIEW

**Comment by sburke781** [comment]
Thanks for finding this.  I am thinking it may be worth leaving it off altogether if we can.  I'll test that and see if it still works.

Simon

**Comment by sburke781** [comment]
Also, are you saying a value of zero leaves the language unchanged?  E.g. for those who may have it set to Swedish it would leave it set that way, and those who have the language configured as English it would leave it set to English?  If not, and from my last comment, if we do in fact need to pass it in, then I am thinking we should offer options for the language or look it up via the API.

**Comment by JasperVanLeeuwen** [comment]
ok ok, I was too lazy ;) the language can be removed altogether :) I updated accordingly

**Comment by sburke781** [comment]
Thanks for the update and the info re the language listing.  So you were able to test it successfully by running a refresh and it didn't change the language?

**Comment by sburke781** [comment]
Ignore my last comment, I'm sure you would have tested it... I'll review it later this evening and merge it in.  Thanks again.

**Comment by JasperVanLeeuwen** [comment]
Concurrent use of melcloud messed up my testing. Leaving it out sets the language to English.
we can either query https://app.melcloud.com/ for languages, or make a hardcoded list

**Comment by sburke781** [comment]
Hmmm... So you are saying if other Europeans have their app set to Swedish or Finnish it would revert their setup to English if we leave out the language?  I am thinking a static list may be enough for now, given the number of users... The ability to draw those from the web site would be nice, but is probably not worth it atm....

**Comment by sburke781** [comment]
I might get a list of the required languages from the Community thread as a start.

**Comment by sburke781** [comment]
I have setup a branch and updated version of the parent driver that includes a language selector in the preferences.  Will see how this goes with some testing by those in Europe.

**Pull request closed without merging**
